version: '3'
services:
    template-jupyterlab-leafmap:
        build:
            context: .
            dockerfile: Dockerfile
        image: tithiwat/template-jupyterlab-leafmap:latest
        restart: unless-stopped
        ports:
          - 8888:8888